$(function() {
    $("#arrowLHam").click(function(){
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();

        $("#VBot").hide(300);
        $("#LHam").toggle(500);
    });

    $("#arrowVBot").click(function(){
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#LHam").hide(300);
        $("#VBot").toggle(500);
    });

    $("#arrowMVer").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#AAlb").hide(300);
        $("#MVer").toggle(500);
    });

    $("#arrowAAlb").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#MVer").hide(300);
        $("#AAlb").toggle(500);
    });

    $("#arrowLNor").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#CSai").hide(300);
        $("#LNor").toggle(500);
    });

    $("#arrowCSai").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#LNor").hide(300);
        $("#CSai").toggle(500);
    });

    $("#arrowSVet").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#CLec").hide(300);
        $("#SVet").toggle(500);
    });

    $("#arrowCLec").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#SVet").hide(300);
        $("#CLec").toggle(500);
    });

    $("#arrowDRic").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#EOco").hide(300);
        $("#DRic").toggle(500);
    });

    $("#arrowEOco").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#DRic").hide(300);
        $("#EOco").toggle(500);
    });
    
    $("#arrowPGas").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#DKvy").hide(300);
        $("#PGas").toggle(500);
    });

    $("#arrowDKvy").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#PGas").hide(300);
        $("#DKvy").toggle(500);
    });

    $("#arrowSPer").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#LStr").hide(300);
        $("#SPer").toggle(500);
    });

    $("#arrowLStr").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#SPer").hide(300);
        $("#LStr").toggle(500);
    });

    $("#arrowKRai").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#AGio").hide(300);
        $("#KRai").toggle(500);
    });

    $("#arrowAGio").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#KRai").hide(300);
        $("#AGio").toggle(500);
    });

    $("#arrowRGro").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#KMag").hide(300);
        $("#RGro").toggle(500);
    });

    $("#arrowKMag").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#GRus").hide();
        $("#NLat").hide();
        
        $("#RGro").hide(300);
        $("#KMag").toggle(500);
    });

    $("#arrowGRus").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        
        $("#NLat").hide(300);
        $("#GRus").toggle(500);
    });

    $("#arrowNLat").click(function(){
        $("#LHam").hide();
        $("#VBot").hide();
        $("#MVer").hide();
        $("#AAlb").hide();
        $("#LNor").hide();
        $("#CSai").hide();
        $("#SVet").hide();
        $("#CLec").hide();
        $("#DRic").hide();
        $("#EOco").hide();
        $("#PGas").hide();
        $("#DKvy").hide();
        $("#SPer").hide();
        $("#LStr").hide();
        $("#KRai").hide();
        $("#AGio").hide();
        $("#RGro").hide();
        $("#KMag").hide();
        
        $("#GRus").hide(300);
        $("#NLat").toggle(500);
    });

});